/**
 * Regression test for: functions.yaml generated by prepare-firebase-deploy.mjs
 * was missing `secretEnvironmentVariables`, causing RESEND_API_KEY to be
 * undefined at Cloud Function runtime — invitation emails were silently skipped.
 *
 * Root cause: the `functionsYaml` template string in the script did not include
 * the `secretEnvironmentVariables` block required by Firebase CLI to inject
 * secrets from Google Cloud Secret Manager at function startup.
 *
 * Fix: Added `secretEnvironmentVariables: - key: RESEND_API_KEY` to the template.
 *
 * @see scripts/prepare-firebase-deploy.mjs
 */

import { describe, it, expect } from 'vitest'
import { readFileSync, existsSync } from 'fs'
import { resolve } from 'path'

const SCRIPT_PATH = resolve(process.cwd(), 'scripts/prepare-firebase-deploy.mjs')
const scriptSource = readFileSync(SCRIPT_PATH, 'utf8')

// ── Extract the functionsYaml template string from the script ──────────────
// This regex captures the entire template literal assigned to `functionsYaml`
// between the backticks, so we validate what actually gets written to disk.
const templateMatch = scriptSource.match(
  /const\s+functionsYaml\s*=\s*`([\s\S]+?)`\s*\n/
)

// ── Source-level checks ────────────────────────────────────────────────────
describe('prepare-firebase-deploy.mjs — source integrity', () => {
  it('script file exists', () => {
    expect(existsSync(SCRIPT_PATH)).toBe(true)
  })

  it('defines a functionsYaml template string', () => {
    expect(templateMatch).not.toBeNull()
  })
})

// ── functions.yaml template content validation ─────────────────────────────
describe('prepare-firebase-deploy.mjs — functions.yaml template', () => {
  const template = templateMatch?.[1] ?? ''

  it('contains specVersion v1alpha1', () => {
    expect(template).toContain('specVersion: v1alpha1')
  })

  it('declares Cloud Run v2 platform', () => {
    expect(template).toContain('platform: gcfv2')
  })

  it('sets entryPoint to "server"', () => {
    expect(template).toContain('entryPoint: server')
  })

  /**
   * REGRESSION: this assertion prevents the bug from returning.
   *
   * Without `secretEnvironmentVariables`, Cloud Functions runtime does NOT
   * inject RESEND_API_KEY from Secret Manager — process.env.RESEND_API_KEY
   * is undefined and emailService.ts skips every email silently.
   */
  it('declares secretEnvironmentVariables block', () => {
    expect(template).toContain('secretEnvironmentVariables:')
  })

  it('registers RESEND_API_KEY as a secret (REGRESSION)', () => {
    // The key must appear as a list item under secretEnvironmentVariables.
    // If this test fails, emails will silently stop sending in production.
    expect(template).toMatch(/secretEnvironmentVariables:\s*\n\s*- key: RESEND_API_KEY/)
  })
})
